services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kmem
      POSTGRES_USER: kmem_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kmem_user -d kmem"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
