name: Gateway CI
on:
  push:
    branches: ["main"]
    paths: "packages/gateway/**"
  pull_request:
    branches: ["main", "feature/gateway"]
    paths: "packages/gateway/**"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/gateway
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: install dependencies
        run: go get -v -t -d ./...
      - name: run test codes
        run: go test ./tests/...
