name: Kmem CI
on:
  push:
    branches: [ main, develop ]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpassword
          POSTGRES_USER: testuser  
          POSTGRES_DB: kmem_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: create test environment
        run: |
          echo "POSTGRES_PASSWORD=testpassword" > .env
          echo "JWT_SECRET_KEY=test-jwt-secret" >> .env
          
          cat > config.yml << EOF
          server:
            port: 8000
            jwtSecret: ""
          postgres:
            host: "localhost"
            port: 5432
            user: "testuser"
            password: ""
            databaseName: "kmem_test"
            sslmode: "disable"
          EOF

      - name: install dependencies
        run: go get -v -t -d ./...

      - name: run tests
        run: go test -v ./tests/...
